apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-app-local-configmap
data:
  MYSQL_HOST: {{ .Values.mysql.host }}
  MYSQL_USER: {{ .Values.mysql.user }}
  MYSQL_DB: {{ .Values.mysql.database }}
