apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app-local
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: app-local
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 3000
        env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-app-local-configmap
              key: MYSQL_HOST
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-app-local-configmap
              key: MYSQL_USER
        - name: MYSQL_DB
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-app-local-configmap
              key: MYSQL_DB
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-app-local-secrets
              key: MYSQL_PASSWORD
