apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-local-service
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}
